project_id = "shmbwdjuddvquszwkvuq"

[functions.generate-strain-image]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.triage-summary]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false