project_id = "shmbwdjuddvquszwkvuq"

[functions.ai-pharmacokinetic-profile]
verify_jwt = false

[functions.treatment-subscription-engine]
verify_jwt = false

[functions.sync-vault-secret]
verify_jwt = false
