import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.42.0";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const PUBMED_API_BASE = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils";

serve(async (req) => {
  try {
    const { query = "cannabinoid OR CBD OR THC OR medical cannabis", max_results = 500 } = await req.json();

    // 1. Search PubMed for IDs
    const searchUrl = `${PUBMED_API_BASE}/esearch.fcgi?db=pubmed&term=${encodeURIComponent(query)}&retmax=${max_results}&retmode=json`;
    const searchRes = await fetch(searchUrl);
    const searchData = await searchRes.json();
    const ids = searchData.esearchresult.idlist;

    if (!ids || ids.length === 0) {
      return new Response(JSON.stringify({ message: "No articles found" }), { status: 200 });
    }

    // 2. Fetch details for each ID (in chunks to avoid URL length limits)
    const chunkSize = 100;
    let importedCount = 0;

    for (let i = 0; i < ids.length; i += chunkSize) {
      const chunkIds = ids.slice(i, i + chunkSize).join(",");
      const summaryUrl = `${PUBMED_API_BASE}/esummary.fcgi?db=pubmed&id=${chunkIds}&retmode=json`;
      const summaryRes = await fetch(summaryUrl);
      const summaryData = await summaryRes.json();

      const articles = Object.values(summaryData.result).filter(item => typeof item === 'object' && item.uid);

      const toInsert = articles.map((art: any) => ({
        title: art.title,
        authors: art.authors?.map((a: any) => a.name).join(", "),
        abstract: art.value || art.fulljournalname, // PubMed Summary API has limited abstract, but we use what we have
        doi: art.elocationid,
        year: art.pubdate?.split(" ")[0],
        keywords: art.source,
        // Embedding will be generated by a separate background process or trigger
      }));

      const { error } = await supabase.from("scientific_articles").upsert(toInsert, { onConflict: 'title' });
      if (error) console.error("Insert error:", error);
      else importedCount += toInsert.length;
    }

    return new Response(JSON.stringify({ message: `Imported ${importedCount} articles`, count: importedCount }), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
});
