-- =====================================================================
-- 1) RPC sign_doctor_contract — assinatura server-side (SHA-512)
-- =====================================================================
CREATE OR REPLACE FUNCTION public.sign_doctor_contract(
  _doctor_id uuid,
  _signer_ip text DEFAULT NULL,
  _signer_user_agent text DEFAULT NULL,
  _contract_version text DEFAULT 'v1.0'
)
RETURNS TABLE(contract_id uuid, sha512_hash text, signed_at timestamptz, signer_ip text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_doctor record;
  v_profile record;
  v_now timestamptz := now();
  v_hash text;
  v_payload text;
  v_id uuid;
  v_ip text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Autenticação obrigatória para assinar o contrato.';
  END IF;

  SELECT id, user_id, crm, crm_state INTO v_doctor
  FROM public.doctors WHERE id = _doctor_id;

  IF v_doctor.id IS NULL THEN
    RAISE EXCEPTION 'Médico não encontrado.';
  END IF;

  IF v_doctor.user_id IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'Apenas o próprio médico pode assinar seu contrato.';
  END IF;

  SELECT full_name, cpf INTO v_profile FROM public.profiles WHERE id = v_uid;

  v_ip := COALESCE(
    NULLIF(split_part(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ',', 1), ''),
    NULLIF(_signer_ip, ''),
    'unknown'
  );

  v_payload := 'CONTRATO-MEDICO-PLANTA-Y-RAIZ|DOC:' || v_doctor.id::text
    || '|USER:' || v_uid::text
    || '|CRM:' || COALESCE(v_doctor.crm, '')
    || '|UF:' || COALESCE(v_doctor.crm_state, '')
    || '|CPF:' || COALESCE(v_profile.cpf, '')
    || '|IP:' || v_ip
    || '|UA:' || COALESCE(_signer_user_agent, '')
    || '|VER:' || COALESCE(_contract_version, 'v1.0')
    || '|DATE:' || v_now::text
    || '|CFM-2336-2023';

  v_hash := upper(encode(sha512(convert_to(v_payload, 'UTF8')), 'hex'));

  INSERT INTO public.doctor_contracts (
    doctor_id, user_id, contract_version, doctor_full_name, doctor_cpf,
    doctor_crm, doctor_crm_uf, status, signed_at, signer_ip, signer_user_agent, sha512_hash
  ) VALUES (
    v_doctor.id, v_uid, COALESCE(_contract_version, 'v1.0'),
    COALESCE(v_profile.full_name, 'Médico(a) Credenciado(a)'),
    COALESCE(v_profile.cpf, '000.000.000-00'),
    COALESCE(v_doctor.crm, ''), COALESCE(v_doctor.crm_state, 'SP'),
    'signed', v_now, v_ip, LEFT(COALESCE(_signer_user_agent, ''), 500), v_hash
  ) RETURNING id INTO v_id;

  UPDATE public.doctors SET is_contract_signed = true WHERE id = v_doctor.id;

  RETURN QUERY SELECT v_id, v_hash, v_now, v_ip;
END;
$$;

REVOKE ALL ON FUNCTION public.sign_doctor_contract(uuid, text, text, text) FROM public;
GRANT EXECUTE ON FUNCTION public.sign_doctor_contract(uuid, text, text, text) TO authenticated;

-- =====================================================================
-- 2) Ledger imutável de blocos clínicos
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.clinical_ehr_blocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  block_index bigint GENERATED BY DEFAULT AS IDENTITY,
  patient_id uuid NOT NULL,
  doctor_id uuid,
  record_type text NOT NULL,
  reference_id uuid,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  prev_hash text,
  block_hash text NOT NULL,
  share_token text UNIQUE,
  share_expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ehr_blocks_patient ON public.clinical_ehr_blocks(patient_id);
CREATE INDEX IF NOT EXISTS idx_ehr_blocks_doctor ON public.clinical_ehr_blocks(doctor_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_ehr_block_hash ON public.clinical_ehr_blocks(block_hash);

GRANT SELECT ON public.clinical_ehr_blocks TO authenticated;
GRANT ALL ON public.clinical_ehr_blocks TO service_role;

ALTER TABLE public.clinical_ehr_blocks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Patients read own ehr blocks" ON public.clinical_ehr_blocks;
CREATE POLICY "Patients read own ehr blocks" ON public.clinical_ehr_blocks
  FOR SELECT TO authenticated USING (patient_id = auth.uid());

DROP POLICY IF EXISTS "Doctors read issued ehr blocks" ON public.clinical_ehr_blocks;
CREATE POLICY "Doctors read issued ehr blocks" ON public.clinical_ehr_blocks
  FOR SELECT TO authenticated USING (
    doctor_id IN (SELECT id FROM public.doctors WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Admins read all ehr blocks" ON public.clinical_ehr_blocks;
CREATE POLICY "Admins read all ehr blocks" ON public.clinical_ehr_blocks
  FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));

-- Imutabilidade absoluta: nenhum UPDATE/DELETE permitido (nem admin)
CREATE OR REPLACE FUNCTION public.block_ehr_ledger_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'Registros do ledger clínico são imutáveis (LGPD/CFM): alteração ou exclusão bloqueada.';
END;
$$;

DROP TRIGGER IF EXISTS trg_ehr_ledger_immutable ON public.clinical_ehr_blocks;
CREATE TRIGGER trg_ehr_ledger_immutable
BEFORE UPDATE OR DELETE ON public.clinical_ehr_blocks
FOR EACH ROW EXECUTE FUNCTION public.block_ehr_ledger_mutation();

-- =====================================================================
-- 3) Reversão manual (Human-in-the-Loop) de ações autônomas de IA
-- =====================================================================
ALTER TABLE public.ai_events ADD COLUMN IF NOT EXISTS reverted_at timestamptz;
ALTER TABLE public.ai_events ADD COLUMN IF NOT EXISTS reverted_by uuid;
ALTER TABLE public.ai_events ADD COLUMN IF NOT EXISTS revert_reason text;

CREATE OR REPLACE FUNCTION public.revert_ai_agent_action(
  _event_id uuid,
  _reason text
)
RETURNS TABLE(event_id uuid, reverted_at timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_now timestamptz := now();
  v_found uuid;
BEGIN
  IF v_uid IS NULL OR NOT public.has_role(v_uid, 'admin') THEN
    RAISE EXCEPTION 'Apenas administradores podem reverter ações de agentes de IA.';
  END IF;

  IF _reason IS NULL OR length(btrim(_reason)) < 5 THEN
    RAISE EXCEPTION 'Informe um motivo auditável para a reversão (mínimo 5 caracteres).';
  END IF;

  UPDATE public.ai_events
  SET reverted_at = v_now, reverted_by = v_uid, revert_reason = btrim(_reason)
  WHERE id = _event_id AND reverted_at IS NULL
  RETURNING id INTO v_found;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Ação de IA não encontrada ou já revertida.';
  END IF;

  INSERT INTO public.audit_log (user_id, action, table_name, record_id, new_data)
  VALUES (v_uid, 'ai_action_reverted', 'ai_events', _event_id,
          jsonb_build_object('reason', btrim(_reason), 'reverted_at', v_now));

  RETURN QUERY SELECT v_found, v_now;
END;
$$;

REVOKE ALL ON FUNCTION public.revert_ai_agent_action(uuid, text) FROM public;
GRANT EXECUTE ON FUNCTION public.revert_ai_agent_action(uuid, text) TO authenticated;